server {
    listen 8080;
    absolute_redirect off;
    server_name _;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;
    location = /healthz { access_log off; return 200 'ok'; }
    location = /videodepth { return 308 /videodepth/$is_args$args; }
    location /videodepth/ {
        try_files $uri $uri/ =404;
        add_header Cache-Control 'no-cache';
    }
    location / { return 404; }
    gzip on;
    gzip_types text/css application/javascript application/json;
}
